// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3NeaMZI47JJI8cdhTKVKMwPDpwkeIr14',
    appId: '1:581299274158:web:841b9fc86071e640f5083f',
    messagingSenderId: '581299274158',
    projectId: 'stillhere-ad395',
    authDomain: 'stillhere-ad395.firebaseapp.com',
    storageBucket: 'stillhere-ad395.firebasestorage.app',
    measurementId: 'G-LK5LMC28V8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS_f8qDg3fYXln__YVi4R6Cbds8Md0sxk',
    appId: '1:581299274158:android:20005635251dbec1f5083f',
    messagingSenderId: '581299274158',
    projectId: 'stillhere-ad395',
    storageBucket: 'stillhere-ad395.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgH-YY7SgnV9NScr1GnZZ5ItKmQKV16-I',
    appId: '1:581299274158:ios:12b7dde61835e0a9f5083f',
    messagingSenderId: '581299274158',
    projectId: 'stillhere-ad395',
    storageBucket: 'stillhere-ad395.firebasestorage.app',
    iosClientId: '581299274158-3bkqfufd1b5nonk2rmgdfvnjfq80nifh.apps.googleusercontent.com',
    iosBundleId: 'com.tr.stillhere.app',
  );
}
